name: Build & Deploy stepwiseAI (GHCR → Lightsail via SSH)

on:
  push:
    branches: [ main ]
    # optional:
    # paths:
    #   - 'stepwiseAI/**'
    #   - 'docker-compose.yml'
    #   - '.github/workflows/deploy-stepwise.yml'

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/keerat21/stepwiseai-backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Lightsail and deploy stepwise
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LIGHTSAIL_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu/apps
            # login to GHCR only if your package is private
            if [ -n "${GHCR_USER:-}" ] && [ -n "${GHCR_PAT:-}" ]; then
              echo "$GHCR_PAT" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
            fi
            IMAGE_TAG=${GITHUB_SHA} docker compose pull stepwise
            IMAGE_TAG=${GITHUB_SHA} docker compose up -d --no-deps stepwise
            docker compose ps
        env:
          GITHUB_SHA: ${{ github.sha }}
          # GHCR_USER: ${{ secrets.GHCR_USER }}    # optional if public package
          # GHCR_PAT: ${{ secrets.GHCR_PAT }}      # optional if public package
